project_id = "crcxjpnbrsdosdlijyqu"

[functions.explain]
verify_jwt = false

[functions.similar]
verify_jwt = false

[functions.submit_attempt]
verify_jwt = false

[functions.fill_answers]
verify_jwt = false
